-- Cyber Spin Wheel Database Setup
CREATE DATABASE IF NOT EXISTS cyber_spin_wheel CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cyber_spin_wheel;
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, user_id VARCHAR(50) UNIQUE NOT NULL, fullname VARCHAR(255) NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, gender VARCHAR(50) NOT NULL, college VARCHAR(255) NOT NULL, campus VARCHAR(50) NOT NULL, role VARCHAR(100) NOT NULL, registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_email (email), INDEX idx_user_id (user_id), INDEX idx_campus (campus), INDEX idx_role (role)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS spin_history (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, prize VARCHAR(255) NOT NULL, spun_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX idx_user_id (user_id), INDEX idx_spun_at (spun_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS wheel_sectors (id INT AUTO_INCREMENT PRIMARY KEY, label VARCHAR(255) NOT NULL, color VARCHAR(7) NOT NULL, text VARCHAR(7) NOT NULL, weight INT DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_label (label)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS campuses (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50) UNIQUE NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS roles (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) UNIQUE NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS genders (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50) UNIQUE NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO campuses (name) VALUES ('MCC'), ('MMC'), ('MBC');
INSERT INTO roles (name) VALUES ('Student'), ('Faculty'), ('Non-Teaching'), ('Others');
INSERT INTO genders (name) VALUES ('Male'), ('Female'), ('Others');
